version: '3.9'
services:
  django:
    image: django-docker:0.0.1
    build:
      context: .
    ports:
      - "8000:8000"
    command: bash -c "python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/djangodocker
    networks:
      - django-network
networks:
  django-network:
    driver: bridge
