# Generated by Django 5.0.2 on 2024-02-27 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('organization_unit_name', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('state_name', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
