# Generated by Django 5.0.2 on 2024-02-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country_name',
            field=models.CharField(max_length=2),
        ),
    ]
